repos:
  # 0) Add uv sync hook to ensure consistent environments
  - repo: local
    hooks:
      - id: uv-sync-check
        name: uv check dependencies
        entry: uv pip freeze
        language: system
        pass_filenames: false  # We don't want pre-commit to pass file names to `uv`
        files: ^(pyproject\.toml|requirements\.lock)$  # Only run if these files are changed

  # 1) Ruff for linting and formatting Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]

  # 2) nbQA to run Ruff on notebooks (and Mypy)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: nbqa-mypy
        args: [--config-file=pyproject.toml]

  # 3) Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        language_version: python3

  # 4) Strip Jupyter notebook outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
        args: [--drop-empty-cells, --strip-init-cells]

  # 5) detect-secrets for finding secrets in ANY file
  - repo: https://github.com/Yelp/detect-secrets
    rev: 'v1.5.0'
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        # exclude: (pattern_here) # e.g., '\.dvc/' or specific test files

  # 6) Spell checking with codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=ba,al,hist,te,teh,nd
          - --skip=*.csv,*.json,*.parquet,*.dvc,uv.lock

  # 7) TOML sorting for pyproject.toml
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        files: ^pyproject\.toml$

  # 8) A handful of generic checks (whitespace, YAML syntax, conflict markers, secrets, large files)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
